### ISSUE TITLE
How to force HTTP

### ISSUE THREAD

**Issue by 403-html** [Xotabu4/inbucket-js-client#6]
Hi,  
I'm using Cypress, doing a simple request and it turns out I have https, not http. How can I force the http?

```ts
    const client = new InbucketAPIClient(Cypress.env('INBUCKET_URL')); // it has `http://`
    const inbox = await client.mailbox(account);
    const message = await client.message(account, inbox[place ?? 0].id);
    const code = message.body.html.match(/\d{6}/g)?.[0];

    return code;
```

But I get `https://` request  
![image](https://user-images.githubusercontent.com/57900160/176182759-52e43ae9-7744-4d5a-b27b-762b5192fa3a.png)  
  
Also question:  
Isn't this package deprecated due to request-promise-native and request being deprecated (vulnerable)?

**Comment by Xotabu4** [comment]
@403-html hi, we will migrate away from request-promise-native
